### ISSUE TITLE
Exception in rop.py

### ISSUE THREAD

**Issue by PoslavskySV** [smangul1/rop#118]
Hi, 

I was using `rop-imrep.sh` script and got the following error before the process finished:

```
BLAST Database error: No alias or index file found for nucleotide database [/local/poslavsky/rnaseq/imrep/rop//db_human/rRNA/rRNA] in search path [/local/poslavsky/rnaseq/imrep/rop/ROP/rop/QC::]
ERROR: Subprocess crashed. 
Traceback (most recent call last):
  File "/home/poslavsky/local/rnaseq/imrep/rop/rop.py", line 69, in <module>
    nReads["rRNA"], n_rRNATotal = step_1c(unmapped_file, readLength)
  File "/local/poslavsky/rnaseq/imrep/rop/rop_functions.py", line 250, in step_1c
    if subprocess.Popen([cmd], shell=True).wait(): raise SubprocessError()
rop_functions.SubprocessError
```

I use the recent version [1.0.7](https://downloads.sourceforge.net/project/rop2/1.0.7/rop.tar.gz) of ROP and these are the exact command I used and the full output:

```bash
./rop-imrep.sh data.sort.bam ROP ""
```

```
ImReP is written by Igor Mandric and Serghei Mangul.
Released under the terms of the General Public License version 3.0 (GPLv3)
For more details see: https://sergheimangul.wordpress.com/rop/
ROP Tutorial: https://github.com/smangul1/rop/wiki 
********************************************************************************
[M::bam2fq_mainloop] processed 8748494 reads
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
[M::bam2fq_mainloop] processed 0 reads
********************************************************************************
ROP (v1.0.6) is a computational protocol aimed to discover the source of all reads, 
originated from complex RNA molecules, recombinant B and T cell receptors and microbial
communities. 

Written by Serghei Mangul (smangul@ucla.edu), Harry Taegyun Yang 
(harry2416@gmail.com), Kevin Hsieh (kevin.hsieh@ucla.edu), and Linus Chen 
(u6.30cl@gmail.com). University of California, Los Angeles (UCLA). (c) 2016. 

Released under the terms of the General Public License version 3.0 (GPLv3)
For more details see: https://sergheimangul.wordpress.com/rop/
ROP Tutorial: https://github.com/smangul1/rop/wiki 
********************************************************************************
Processing 8748494 unmapped reads of length 50.
1. Quality Control...
--filtered 2281221 low quality reads
--filtered 64814 low complexity reads (e.g. ACACACAC...)
BLAST Database error: No alias or index file found for nucleotide database [/local/poslavsky/rnaseq/imrep/rop//db_human/rRNA/rRNA] in search path [/local/poslavsky/rnaseq/imrep/rop/ROP/rop/QC::]
ERROR: Subprocess crashed. 
Traceback (most recent call last):
  File "/home/poslavsky/local/rnaseq/imrep/rop/rop.py", line 69, in <module>
    nReads["rRNA"], n_rRNATotal = step_1c(unmapped_file, readLength)
  File "/local/poslavsky/rnaseq/imrep/rop/rop_functions.py", line 250, in step_1c
    if subprocess.Popen([cmd], shell=True).wait(): raise SubprocessError()
rop_functions.SubprocessError
```

The BAM file was prepared using STAR as follows:

```
STAR --readFilesCommand zcat --runThreadN 16 --genomeDir path/to/hg37 --outSAMtypels  BAM SortedByCoordinate --outSAMunmapped Within --outStd BAM_SortedByCoordinate --readFilesIn data_R1.fastq.gz data_R2.fastq.gz > data.sort.bam
```

Can you help me to overcome this trouble?

Thanks!

**Comment by PoslavskySV** [comment]
just noticed that the index file for my BAM may be corrupted, so I've regenerated index using samtools 
```
tools/samtools index data.sort.bam
```

but the error still the same: 

```
********************************************************************************
rop-imrep.sh is now available under ROP release v1.0.7
rop-imrep.sh is a script to run ROP-ImReP for bam file with mixture of mapped and unmapped reads.
ImReP is written by Igor Mandric and Serghei Mangul.
Released under the terms of the General Public License version 3.0 (GPLv3)
For more details see: https://sergheimangul.wordpress.com/rop/
ROP Tutorial: https://github.com/smangul1/rop/wiki 
********************************************************************************
[M::bam2fq_mainloop] processed 8748494 reads
[main_samview] region "14:106032614-107288051" specifies an unknown reference name. Continue anyway.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] region "2:89156874-89630436" specifies an unknown reference name. Continue anyway.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] region "22:22380474-23265085" specifies an unknown reference name. Continue anyway.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] region "14:22090057-23021075" specifies an unknown reference name. Continue anyway.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] region "7:141998851-142510972" specifies an unknown reference name. Continue anyway.
[M::bam2fq_mainloop] processed 0 reads
[main_samview] region "7:38279625-38407656" specifies an unknown reference name. Continue anyway.
[M::bam2fq_mainloop] processed 0 reads
********************************************************************************
ROP (v1.0.6) is a computational protocol aimed to discover the source of all reads, 
originated from complex RNA molecules, recombinant B and T cell receptors and microbial
communities. 

Written by Serghei Mangul (smangul@ucla.edu), Harry Taegyun Yang 
(harry2416@gmail.com), Kevin Hsieh (kevin.hsieh@ucla.edu), and Linus Chen 
(u6.30cl@gmail.com). University of California, Los Angeles (UCLA). (c) 2016. 

Released under the terms of the General Public License version 3.0 (GPLv3)

For more details see: https://sergheimangul.wordpress.com/rop/
ROP Tutorial: https://github.com/smangul1/rop/wiki 
********************************************************************************
Processing 8748494 unmapped reads of length 50.
1. Quality Control...
--filtered 2281221 low quality reads
--filtered 64814 low complexity reads (e.g. ACACACAC...)
BLAST Database error: No alias or index file found for nucleotide database [/local/poslavsky/rnaseq/imrep/rop//db_human/rRNA/rRNA] in search path [/local/poslavsky/rnaseq/imrep/rop/ROP/rop/QC::]
ERROR: Subprocess crashed. 
Traceback (most recent call last):
  File "/home/poslavsky/local/rnaseq/imrep/rop/rop.py", line 69, in <module>
    nReads["rRNA"], n_rRNATotal = step_1c(unmapped_file, readLength)
  File "/local/poslavsky/rnaseq/imrep/rop/rop_functions.py", line 250, in step_1c
    if subprocess.Popen([cmd], shell=True).wait(): raise SubprocessError()
rop_functions.SubprocessError
```

**Comment by kahsieh** [comment]
Hello,
Have you successfully downloaded the database using getDB.py?

**Comment by smangul1** [comment]
i think the problem is that the names of chr are "chr1"  but not "1". We will have a version of "chr1" in the new release which will be available by the end of the week 

Serghei

**Comment by PoslavskySV** [comment]
The problem was in the database location. I downloaded it with `python getDB.py ~/`, but for some reason the script is looking it in the current directory, so I have to put symbolic link in the current directory like so: 

```
ln -s ~/db_human db_human
```

and this worked out for me.
